### ISSUE TITLE
layer DarknetShortcut not exists or registered

### ISSUE THREAD

**Issue by xskxushaokai** [xiangweizeng/darknet2ncnn#10]
您好，我在用ncnn加载转换后的模型时，DarknetShortcut层加载不进来：layer DarknetShortcut not exists or registered。
是要修改ncnn源码调用您自定义的darknet_shortcut.cpp进行加载吗？

**Comment by xiangweizeng** [comment]
DarknetShortcut 是自定义添加的， 使用时你需要将其注册到ncnn network中， 具体的你可以参考example/yolo.cpp
```
  CustomizedNet yolo;
  register_darknet_layer(yolo);
  yolo.load_param(param);
```
