### ISSUE TITLE
关于安卓版本库

### ISSUE THREAD

**Issue by popper0912** [xiangweizeng/darknet2ncnn#11]
您好，可否将源码编译一个安卓版本的算法库啊，直接调用您例子中yolov2.cpp中的函数，方便安卓移植。我现在将相关源码放在AS中进行编译，总是会出现问题。
yolov2.cpp中的函数
  CustomizedNet yolo;
  register_darknet_layer(yolo);
  yolo.load_param(param);
  yolo.load_model(bin);

**Comment by rockygao123** [comment]
我也想知道，现在有方案了吗？

**Comment by paleomoon** [comment]
[darknet2ncnn-android](https://github.com/paleomoon/darknet2ncnn-android)

**Comment by xiangweizeng** [comment]
ncnn merged darknet layers, https://github.com/xiangweizeng/ncnn
