### ISSUE TITLE
how to solve it？

### ISSUE THREAD

**Issue by MaxwellAlen** [xiangweizeng/darknet2ncnn#16]
maxwell@maxwell#：./yolo zoo/yolov3-tiny.param  zoo/yolov3-tiny.bin  data/dog.jpg 
  data/coco.names

ModelBin read weight_data failed 0
layer load_model 33 failed
Segmentation fault (core dumped)

**Comment by ZhengXing-shawn** [comment]
Save problem.
Replace 'yolov3-tiny.bin' and 'yolov3-tiny.param' at ./example/zoo  with the same file download from the baiduyun link. And then it work.

**Comment by MaxwellAlen** [comment]
yeah.it worked. thannnnkyou!
---原始邮件---
发件人:"ZhengXing-shawn"<notifications@github.com>;
发送时间:2019年6月10日(星期一) 中午1:51
收件人:"xiangweizeng/darknet2ncnn"<darknet2ncnn@noreply.github.com>;
抄送人:"Maxwell"<870678030@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [xiangweizeng/darknet2ncnn] how to solve it？ (#16)


Save problem.
 Replace 'yolov3-tiny.bin' and 'yolov3-tiny.param' at ./example/zoo  with the same file download from the baiduyun link. And then it work.
 
&mdash;
