### ISSUE TITLE
when i run yolo here is a error?? 

### ISSUE THREAD

**Issue by MaxwellAlen** [xiangweizeng/darknet2ncnn#17]
liu@Sir:~/darknet2ncnn/example$ ./yolo zoo/yolov3-tiny.param zoo/yolov3-tiny.bin data/dog.jpg data/coco.names
Bus error (core dumped)

**Comment by xiangweizeng** [comment]
Bus error 一般是有内存对齐导致的，具体情况需要结合ncnn及操作系统平台及硬件CPU进行分析。
