### ISSUE TITLE
跑示例程序成功，训练自己的模型后，能转换成功，可以跑，但是检测结果相较与caffe检测框要小的多，不准，我这要调什么参数吗？

### ISSUE THREAD

**Issue by mhsszm** [xiangweizeng/darknet2ncnn#19]

**Comment by xiangweizeng** [comment]
你好， 可以提供具体的样例吗， 对比分析后才能进一步分析呢。

**Comment by mhsszm** [comment]
链接: https://pan.baidu.com/s/1Jxd9_ZzHY6xmHyFx6jYuiA 提取码: i37j 测试结果放在这了，比如图片4.jpg dark-yolov3-tiny出来的结果：0.225451  0.180080  0.609995 0.779379， ncnn-dark-yolov3-tiny出来的结果， 0.225824, 0.313775 0.612129,0.660426

**Comment by mhsszm** [comment]
模型及测试结果放在这了链接: https://pan.baidu.com/s/173tm-pLz-KHZBZ_oINDr6w  提取码: px22  ，比如图片4.jpg dark-yolov3-tiny出来的结果：0.225451 0.180080 0.609995 0.779379， ncnn-dark-yolov3-tiny出来的结果， 0.225824, 0.313775 0.612129,0.660426，这里y1偏大，而y2偏小

**Comment by mhsszm** [comment]
其中两个filters=255改为了filters=24 ，不知道会不会影响，类别从20改为了3,其余都一致。

**Comment by xiangweizeng** [comment]
具体情况需要进一步了解， 欢迎进入群聊  852287556

**Comment by mhsszm** [comment]
好的
