### ISSUE TITLE
darknet2ncnn模型转换时bug

### ISSUE THREAD

**Issue by foolfrog** [xiangweizeng/darknet2ncnn#21]

**Comment by foolfrog** [comment]
make yolov3-tiny.net 命令执行时，如果input size w!=h的时候，会出现bug，原因是ncnn_tools.h第51行：cv::Mat dest(net_w, net_h, CV_8UC3, cv::Scalar(128, 128, 128));应该改为cv::Mat dest(net_h, net_w, CV_8UC3, cv::Scalar(128, 128, 128));

**Comment by xiangweizeng** [comment]
That's right, fixed it,  thank you!
