### ISSUE TITLE
Compilation error, compiler version problem

### ISSUE THREAD

**Issue by yuzuruhanyu** [xiangweizeng/darknet2ncnn#22]
This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++1 or -std=gnu++11 compiler options.

**Comment by xiangweizeng** [comment]
Hello, our program does not need to rely on C++11. can you describe the operation process in detail? 
你好，我们的程序不需要依赖c++ 11。你能详细描述一下操作过程吗?

**Comment by yuzuruhanyu** [comment]
按照readme里面的步骤执行的，因为size_t和mutex类型不支持，在thread_tools.h中include了stdlib.h和mutex

**Comment by xiangweizeng** [comment]
使用最新代码，同时保证ncnn 编译正常，并成功安装到指定目录， 欢迎进入QQ交流群,

**Comment by jackhouchina** [comment]
/darknet2ncnn: error while loading shared libraries: libdarknet.so: cannot open shared object file: No such file or directory

**Comment by xiangweizeng** [comment]
Please refer to https://github.com/xiangweizeng/darknet2ncnn/issues/1#issuecomment-437639532
