### ISSUE TITLE
result boundingbox overlap

### ISSUE THREAD

**Issue by zhanglaplace** [xiangweizeng/darknet2ncnn#25]
![image](https://user-images.githubusercontent.com/12178974/63515918-7e4a4c80-c51e-11e9-8fbc-b2cbe0c1bdd4.png)
你好，我这边用yolov3-tiny测试了一张图，发现person和dog以及truck的iou输出还是有所重叠。是需要进行二次IOU吗。

**Comment by xiangweizeng** [comment]
你好， 你可以将 NMS 的值设置小一些， 这里出来两个目标，是由于没有满足抑制条件， 例如dog, 降低nms参数， 可以进行nms 时可以去掉的

**Comment by xiangweizeng** [comment]
你好， 你可以将 NMS 的值设置小一些， 这里出来两个目标，是由于没有满足抑制条件， 例如dog, 降低nms参数， 进行nms 时可以去掉的

**Comment by zhanglaplace** [comment]
@xiangweizeng 嗯，尝试的修改了yolov3_detection.cpp中的nms_threshold,结果基本是没有变化的。我想想后续再做一次筛选吧，结果框很少的情况下速度应该没有影响。除此之外，想请教下yolov3_tiny的模型是官方的训练方法训练出来的吗。

**Comment by xiangweizeng** [comment]
修改  param文件中的配置即可， 这里才生效， 这个模型就是官方的原始模型

**Comment by zhanglaplace** [comment]
@xiangweizeng 嗯，可以了。多谢～
![image](https://user-images.githubusercontent.com/12178974/63567846-bb0d5680-c5a5-11e9-9f9e-b39ddbdf5de2.png)

**Comment by wanzghen0123** [comment]
> @xiangweizeng 嗯，可以了。多谢～
> ![image](https://user-images.githubusercontent.com/12178974/63567846-bb0d5680-c5a5-11e9-9f9e-b39ddbdf5de2.png)

你好，我也遇到了框的大小不对和一个目标出现两个框的问题。请问具体在哪里修改iou和nms阈值啊？

**Comment by zhanglaplace** [comment]
@wanzghen0123 转化的ncnn的param中最后一个layer有几个参数是confidence和nms的好像，直接修改这里面的值即可
