### ISSUE TITLE
difference between yolov3_detection.h and yolov3detectionoutput.h

### ISSUE THREAD

**Issue by pfeatherstone** [xiangweizeng/darknet2ncnn#27]
What is the difference between the yolov3_detection.h layer defined in this repository that must be registered and the yolov3detectionoutput.h layer already defined in the tencent/ncnn repository. Is this repository out of date?

**Comment by xiangweizeng** [comment]
When our program implements yolov3, NCNN does not support YOLOv3. The two implementations are basically equivalent. You can modify the model conversion code or directly modify the output layer parameters to use the NCNN implementation.
