### ISSUE TITLE
ncnn error -100

### ISSUE THREAD

**Issue by lyolve** [xiangweizeng/darknet2ncnn#28]
ncnn error:-100
what happening?

**Comment by xiangweizeng** [comment]
需要定位具体出现错误的网络层， 如果是YOLO网络层，那么很可能是算法没有检测到目标， 返回了-100的错误。

**Comment by lizozom** [comment]
@xiangweizeng if no objects are detected, should I expect a -100 error code? 

Is there a way to distinguish this from an empty input matrix or other errors? 

Also, how would one determine the layer from which the error is returned?
