### ISSUE TITLE
ncnn error ：-100

### ISSUE THREAD

**Issue by wg1996** [xiangweizeng/darknet2ncnn#3]
When use the example ,this error occured when I use the model of the converted yolov2 , which is trained by darknet. But the yolov2-tiny model can work. Thank you for reply.

**Comment by xiangweizeng** [comment]
When I test, yolov2 is working, you can use `convert_verify` to check whether the conversion is normal.
```
./convert_verify [darknet.cfg] [darknet.weights] [ncnn.param] [ncnn.bin]
```

**Comment by wg1996** [comment]
I had used this command, the result is normal. And the model provided by the yolo's author can work, but the model trained by myself  will occur this error.

**Comment by xiangweizeng** [comment]
Hi , Do you use the new base network or use the original network structure of the yolo author? If it is a new network structure, there should be a problem with the converted parameters. You need to find the layer with the error and adjust its parameters.

**Comment by wg1996** [comment]
Thank you for your kind answer, I will try your suggestion.
