### ISSUE TITLE
First section must be [net] or [network]: 

### ISSUE THREAD

**Issue by zhaojc001** [xiangweizeng/darknet2ncnn#30]
when i run make yolov3-tiny.net ，it appears the following error，please help me.
./darknet2ncnn data/yolov3-tiny.cfg  data/yolov3-tiny.weights example/zoo/yolov3-tiny.param  example/zoo/yolov3-tiny.bin 
First section must be [net] or [network]: Success
darknet2ncnn: ./src/utils.c:256: error: Assertion `0' failed.
Makefile:58: recipe for target 'yolov3-tiny.net' failed
make: *** [yolov3-tiny.net] Aborted (core dumped)

**Comment by xiangweizeng** [comment]
The encoding of the CFG file is not recognized, please try to change it, thank you.




------------------ 原始邮件 ------------------
发件人: "zhaojc001"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 上午9:49
收件人: "xiangweizeng/darknet2ncnn"<darknet2ncnn@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [xiangweizeng/darknet2ncnn] one question (#30)




when i run make yolov3-tiny.net ，it appears the following error，please help me.
 ./darknet2ncnn data/yolov3-tiny.cfg  data/yolov3-tiny.weights example/zoo/yolov3-tiny.param  example/zoo/yolov3-tiny.bin
 First section must be [net] or [network]: Success
 darknet2ncnn: ./src/utils.c:256: error: Assertion `0' failed.
 Makefile:58: recipe for target 'yolov3-tiny.net' failed
 make: *** [yolov3-tiny.net] Aborted (core dumped)

**Comment by zhaojc001** [comment]
I test the error is the same,when I change the dir of the cfg.please help me again.
./darknet2ncnn yolov3-tiny.cfg  yolov3-tiny.weights yolov3-tiny.param yolov3-tiny.bin 
First section must be [net] or [network]: Success
darknet2ncnn: ./src/utils.c:256: error: Assertion `0' failed.
Makefile:58: recipe for target 'yolov3-tiny.net' failed
make: *** [yolov3-tiny.net] Aborted (core dumped)

**Comment by xiangweizeng** [comment]
CFG配置文件的文字编码daknet无法识别，导致网络模型在dakent无法加载，使用assic编码即可，请不要将文件拷贝到Windows，这样会引发编码改变，导致darkent无法识别，希望能帮到你，谢谢。

**Comment by zhaojc001** [comment]
the problem is solved,thank you very much.
