### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by zhaojc001** [xiangweizeng/darknet2ncnn#31]
Is the ncnn supported the windows os?
I compile the ncnn,I use cmake,it appears the following error:
Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.16299.
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Warning at tools/caffe/CMakeLists.txt:12 (message):
  Protobuf not found, caffe model convert tool won't be built
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Warning at tools/onnx/CMakeLists.txt:12 (message):
  Protobuf not found, onnx model convert tool won't be built
I use the add entry,add the path,but the error is continue,please help me.

**Comment by xiangweizeng** [comment]
Ncnn supports windows operating system, caffe2ncnn conversion tool needs to rely on protobuf, you can close it in CMakeList.txt.

**Comment by zhaojc001** [comment]
the method is effective,but  i have compiled the ncnn,when i run yolov3-tiny ,using yolov3-tiny.param and yolov3-tiny.bin,it appears the following error：
DarknetActivation not exists or registered.
please this error is how to solve.

**Comment by zhaojc001** [comment]
the method is effective,but  i have compiled the ncnn,when i run yolov3-tiny ,using yolov3-tiny.param and yolov3-tiny.bin,it appears the following error：
DarknetActivation not exists or registered.
please this error is how to solve.

**Comment by zhaojc001** [comment]
the method is effective,but  i have compiled the ncnn,when i run yolov3-tiny ,using yolov3-tiny.param and yolov3-tiny.bin,it appears the following error：
DarknetActivation not exists or registered.
please this error is how to solve.

**Comment by xiangweizeng** [comment]
use the NCNN, merged darknet layers https://github.com/xiangweizeng/ncnn
