### ISSUE TITLE
rk3288 Total Diff nan Avg Diff: nan

### ISSUE THREAD

**Issue by wanzghen0123** [xiangweizeng/darknet2ncnn#32]
在rk3288上编译报错，麻烦看一下

**Comment by xiangweizeng** [comment]
先验证在rk3288上 darknet是否正常运行, 我猜这里应该是32位系统加载64位系统的模型导致的， darknet本身的bug, 你可以在64位系统做模型转换，转换后的ncnn模型在32位系统是可正常运行的

**Comment by wanzghen0123** [comment]
好的，大佬。我在rk3288上面的测试tiny-yolov3，单张检测时间要3秒，太慢了

**Comment by wanzghen0123** [comment]
> 先验证在rk3288上 darknet是否正常运行, 我猜这里应该是32位系统加载64位系统的模型导致的， darknet本身的bug, 你可以在64位系统做模型转换，转换后的ncnn模型在32位系统是可正常运行的

好的，解决了。请问一下，有相关的项目使用文档说明吗？最近在学习yolov3-tiny在rk3288上的部署。这是我的邮箱：15843062831@163.com

**Comment by xiangweizeng** [comment]
模型转换已经在项目说明中，具体使用，参考NCNN文档即可
