### ISSUE TITLE
转换自己darknet模型，进行视频检测时报错：段错误 (核心已转储)

### ISSUE THREAD

**Issue by wanzghen0123** [xiangweizeng/darknet2ncnn#35]
/darknet2ncnn/example$下 执行：./yolo zoo/yolov3-tiny.param  zoo/yolov3-tiny.bin  data/dog.jpg  data/objects.names

结果如下：
10 [range hood      ] = 0.35896 at -57.80 -418.17 258.84 x 1813.42
19 [shoe cabinet    ] = 0.28689 at 217.76 193.62 375.95 x 304.55
10 [range hood      ] = 0.31165 at -128.09 114.08 443.21 x 741.05
10 [range hood      ] = 0.26759 at 5.88 -347.49 316.14 x 1676.83
10 [range hood      ] = 0.25045 at -32.94 92.90 433.79 x 792.78
10 [range hood      ] = 0.26288 at -60.36 -608.99 271.91 x 2195.61
10 [range hood      ] = 0.28866 at -58.24 -533.50 263.50 x 2046.67
10 [range hood      ] = 0.26968 at 51.96 -3.40 250.54 x 963.64
10 [range hood      ] = 0.39618 at 48.71 14.22 249.38 x 938.48
段错误 (核心已转储)

而且结果完全不对，请问是什么原因？

**Comment by xiangweizeng** [comment]
NCNN错误检查，常见错误看这里， 有问题先看一下这个表单
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result
