### ISSUE TITLE
layer DarknetShortcut not exists or registered？

### ISSUE THREAD

**Issue by zhoujinhai** [xiangweizeng/darknet2ncnn#36]
我训练好模型后用darknet2ncnn能成功转为bin和param，但运行检测后提示layer DarknetShortcut not exists or registered，我看在```darknet2ncnn/src/register_darknet.cpp```文件中有注册，请问这个有好的建议吗？
```c++
void register_darknet_layer(ncnn::Net &net)
{
  net.register_custom_layer("DarknetActivation", ncnn::DarknetActivation_layer_creator);
  net.register_custom_layer("DarknetShortcut", ncnn::DarknetShortcut_layer_creator);
  net.register_custom_layer("Yolov1Detection", ncnn::Yolov1Detection_layer_creator);
  net.register_custom_layer("Yolov3Detection", ncnn::Yolov3Detection_layer_creator);
}```

**Comment by xiangweizeng** [comment]
需要调用register_darknet_layer 将操作注册到网络中， 具体参考example 中的例子。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhoujinhai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 上午9:14
收件人:&nbsp;"xiangweizeng/darknet2ncnn"<darknet2ncnn@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xiangweizeng/darknet2ncnn] layer DarknetShortcut not exists or registered？ (#36)




我训练好模型后用darknet2ncnn能成功转为bin和param，但运行检测后提示layer DarknetShortcut not exists or registered，我看在darknet2ncnn/src/register_darknet.cpp文件中有注册，请问这个有好的建议吗？
 void register_darknet_layer(ncnn::Net &amp;net) {   net.register_custom_layer("DarknetActivation", ncnn::DarknetActivation_layer_creator);   net.register_custom_layer("DarknetShortcut", ncnn::DarknetShortcut_layer_creator);   net.register_custom_layer("Yolov1Detection", ncnn::Yolov1Detection_layer_creator);   net.register_custom_layer("Yolov3Detection", ncnn::Yolov3Detection_layer_creator); }```

**Comment by zhoujinhai** [comment]
是这样的 我在您的这个工程下将模型转换成bin和param， 然后到[ncnn](https://github.com/Tencent/ncnn)工程下运行，我在yolov3.cpp中对应位置添加
```c++
net.register_custom_layer("DarknetActivation", ncnn::DarknetActivation_layer_creator);
  net.register_custom_layer("DarknetShortcut", ncnn::DarknetShortcut_layer_creator);
  net.register_custom_layer("Yolov1Detection", ncnn::Yolov1Detection_layer_creator);
  net.register_custom_layer("Yolov3Detection", ncnn::Yolov3Detection_layer_creator);
```
执行后提示```error: ‘DarknetActivation_layer_creator’ is not a member of ‘ncnn’```？

yolov3.cpp
```c++
 ncnn::Net yolov3;

#if NCNN_VULKAN
    yolov3.opt.use_vulkan_compute = true;
#endif // NCNN_VULKAN

    // original pretrained model from https://github.com/eric612/MobileNet-YOLO
    // param : https://drive.google.com/open?id=1V9oKHP6G6XvXZqhZbzNKL6FI_clRWdC-
    // bin : https://drive.google.com/open?id=1DBcuFCr-856z3FRQznWL_S5h-Aj3RawA

    yolov3.register_custom_layer("DarknetActivation", ncnn::DarknetActivation_layer_creator);
    yolov3.register_custom_layer("DarknetShortcut", ncnn::DarknetShortcut_layer_creator);
    yolov3.register_custom_layer("Yolov1Detection", ncnn::Yolov1Detection_layer_creator);
    yolov3.register_custom_layer("Yolov3Detection", ncnn::Yolov3Detection_layer_creator);

    yolov3.load_param("../model/yolov3-tiny.param");
    yolov3.load_model("../model/yolov3-tiny.bin");
```

**Comment by xiangweizeng** [comment]
关于最终的部署， 可以使用合并darknet layers 后的ncnn, 将定期同步保持和ncnn官方版最新一致，地址:https://github.com/xiangweizeng/ncnn

**Comment by xiangweizeng** [comment]
使用合并后的ncnn,  不在需要注册自定义层

**Comment by zhoujinhai** [comment]
> 使用合并后的ncnn, 不在需要注册自定义层

好的 非常感谢 我去试试

**Comment by zhoujinhai** [comment]
我用您的ncnn编译后，执行图片，出现以下错误，您以前有遇到过吗？
```c++
~/DLStudy/zengNcnn/build/examples$ ./yolov3 000077.jpg 
find_blob_index_by_name detection_out failed
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

```
