### ISSUE TITLE
does  it have cmakelist ver?

### ISSUE THREAD

**Issue by zhangcj13** [xiangweizeng/darknet2ncnn#4]
does  it have cmakelist.ver?
请问有用cmake的版本么?

想在win上进行darknet2ncnn的数据转换
但是darknet为x64,  ncnn生成库为win32, 如何完成数据转换?

**Comment by xiangweizeng** [comment]
目前不支持使用cmake， 也没有win的版本，推荐使用 virtual machine 或者 docker来进行构建， 使用ubuntu 16.04 的镜像即可， 希望能帮到你
