### ISSUE TITLE
转化yolov3模型的问题

### ISSUE THREAD

**Issue by skybocai** [xiangweizeng/darknet2ncnn#43]
make yolov3.net
./darknet2ncnn data/yolov3.cfg  data/yolov3.weights example/zoo/yolov3.param  example/zoo/yolov3.bin 
First section must be [net] or [network]: Success
darknet2ncnn: ./src/utils.c:256: error: Assertion `0' failed.
Makefile:58: recipe for target 'yolov3.net' failed
make: *** [yolov3.net] Aborted (core dumped)
我不知道是因为我的make命令错了还是我的模型的问题

**Comment by xiangweizeng** [comment]
文本编码有问题，导致程序无法识别

**Comment by skybocai** [comment]
谢谢，问题解决了，我的cfg文件是windows 的编码格式，改成unix就成功了
