### ISSUE TITLE
darknet2ncnn: ./src/utils.c: 256: error: Assertion '0' failed.

### ISSUE THREAD

**Issue by xskxushaokai** [xiangweizeng/darknet2ncnn#8]
Thanks to provide the source! Hope your reply!

I convert the exam pleyolov3-tiny successful, but when I convert my own yolov3 model, I recipe the message: First section must bu [net] or [network]: Success.
darknet2ncnn: ./src/utils.c: 256: error: Assertion '0' failed.
Aborted (core dumped).

Is there anyting mistake? What can I do?

**Comment by xiangweizeng** [comment]
Please check if your network model is feasible, the error location is in darknet's src/parser.c
750 |  
751 | section *s = (section *)n->val;
752 | list *options = s->options;
753 | if(!is_network(s)) error("First section must be [net] or [network]");
754 | parse_net_options(options, net);
755 |  
756 | params.h = net->h;

tip:
```
./darknet2ncnn data/cifar.cfg  data/cifar.backup example/zoo/cifar.param  example/zoo/cifar.bin 
              darknet.cfg         darknet.weights        ncnn.param         ncnn.bin
```

Hope it helps you！

**Comment by xskxushaokai** [comment]
> Please check if your network model is feasible, the error location is in darknet's src/parser.c
> 750 |  
> 751 | section *s = (section *)n->val;
> 752 | list *options = s->options;
> 753 | if(!is_network(s)) error("First section must be [net] or [network]");
> 754 | parse_net_options(options, net);
> 755 |  
> 756 | params.h = net->h;
> 
> tip:
> 
> ```
> ./darknet2ncnn data/cifar.cfg  data/cifar.backup example/zoo/cifar.param  example/zoo/cifar.bin 
>               darknet.cfg         darknet.weights        ncnn.param         ncnn.bin
> ```
> Hope it helps you！

我的模型是修改了yolov3原版的检测类别数，然后自己在pytorch下训练的参数，保存格式是.weights，在pytorch中加载参数是没问题的。
cfg的前几行如下：
[net]
# Testing
batch=1
subdivisions=8
# Training
# batch=32
# subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 500200
max_epochs = 800
policy=steps
steps=400000,450000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

# Downsample

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

**Comment by xiangweizeng** [comment]
> > Please check if your network model is feasible, the error location is in darknet's src/parser.c
> > 750 |  
> > 751 | section *s = (section *)n->val;
> > 752 | list *options = s->options;
> > 753 | if(!is_network(s)) error("First section must be [net] or [network]");
> > 754 | parse_net_options(options, net);
> > 755 |  
> > 756 | params.h = net->h;
> > tip:
> > ```
> > ./darknet2ncnn data/cifar.cfg  data/cifar.backup example/zoo/cifar.param  example/zoo/cifar.bin 
> >               darknet.cfg         darknet.weights        ncnn.param         ncnn.bin
> > ```
> > Hope it helps you！
> 
> 我的模型是修改了yolov3原版的检测类别数，然后自己在pytorch下训练的参数，保存格式是.weights，在pytorch中加载参数是没问题的。
> cfg的前几行如下：
> [net]
> 
> # Testing
> batch=1
> subdivisions=8
> 
> # Training
> # batch=32
> # subdivisions=16
> width=416
> height=416
> channels=3
> momentum=0.9
> decay=0.0005
> angle=0
> saturation = 1.5
> exposure = 1.5
> hue=.1
> 
> learning_rate=0.001
> burn_in=1000
> max_batches = 500200
> max_epochs = 800
> policy=steps
> steps=400000,450000
> scales=.1,.1
> 
> [convolutional]
> batch_normalize=1
> filters=32
> size=3
> stride=1
> pad=1
> activation=leaky
> 
> # Downsample
> [convolutional]
> batch_normalize=1
> filters=64
> size=3
> stride=2
> pad=1
> activation=leaky
> 
> [convolutional]
> batch_normalize=1
> filters=32
> size=1
> stride=1
> pad=1
> activation=leaky

看文件内容是没有问题的， 转换时是否将 darknet.cfg 作为了第一个命令行参数呢？
加载模型使用了darknet 的原生接口， 你可尝试使用darknet 来加载你模型试试，如果还是有问题， 考虑是否文件编码的问题了

**Comment by xskxushaokai** [comment]
> > > Please check if your network model is feasible, the error location is in darknet's src/parser.c
> > > 750 |  
> > > 751 | section *s = (section *)n->val;
> > > 752 | list *options = s->options;
> > > 753 | if(!is_network(s)) error("First section must be [net] or [network]");
> > > 754 | parse_net_options(options, net);
> > > 755 |  
> > > 756 | params.h = net->h;
> > > tip:
> > > ```
> > > ./darknet2ncnn data/cifar.cfg  data/cifar.backup example/zoo/cifar.param  example/zoo/cifar.bin 
> > >               darknet.cfg         darknet.weights        ncnn.param         ncnn.bin
> > > ```
> > > Hope it helps you！
> > 
> > 
> > 我的模型是修改了yolov3原版的检测类别数，然后自己在pytorch下训练的参数，保存格式是.weights，在pytorch中加载参数是没问题的。
> > cfg的前几行如下：
> > [net]
> > # Testing
> > batch=1
> > subdivisions=8
> > # Training
> > # batch=32
> > # subdivisions=16
> > width=416
> > height=416
> > channels=3
> > momentum=0.9
> > decay=0.0005
> > angle=0
> > saturation = 1.5
> > exposure = 1.5
> > hue=.1
> > learning_rate=0.001
> > burn_in=1000
> > max_batches = 500200
> > max_epochs = 800
> > policy=steps
> > steps=400000,450000
> > scales=.1,.1
> > [convolutional]
> > batch_normalize=1
> > filters=32
> > size=3
> > stride=1
> > pad=1
> > activation=leaky
> > # Downsample
> > [convolutional]
> > batch_normalize=1
> > filters=64
> > size=3
> > stride=2
> > pad=1
> > activation=leaky
> > [convolutional]
> > batch_normalize=1
> > filters=32
> > size=1
> > stride=1
> > pad=1
> > activation=leaky
> 
> 看文件内容是没有问题的， 转换时是否将 darknet.cfg 作为了第一个命令行参数呢？
> 加载模型使用了darknet 的原生接口， 你可尝试使用darknet 来加载你模型试试，如果还是有问题， 考虑是否文件编码的问题了

我是 参考您的example来运行的 ：./darknet2ncnn data/rw_logo.cfg data/000800.weights data/logo.param data/logo.bin

我试一下用darknet加载模型。

**Comment by xskxushaokai** [comment]
> > > Please check if your network model is feasible, the error location is in darknet's src/parser.c
> > > 750 |  
> > > 751 | section *s = (section *)n->val;
> > > 752 | list *options = s->options;
> > > 753 | if(!is_network(s)) error("First section must be [net] or [network]");
> > > 754 | parse_net_options(options, net);
> > > 755 |  
> > > 756 | params.h = net->h;
> > > tip:
> > > ```
> > > ./darknet2ncnn data/cifar.cfg  data/cifar.backup example/zoo/cifar.param  example/zoo/cifar.bin 
> > >               darknet.cfg         darknet.weights        ncnn.param         ncnn.bin
> > > ```
> > > Hope it helps you！
> > 
> > 
> > 我的模型是修改了yolov3原版的检测类别数，然后自己在pytorch下训练的参数，保存格式是.weights，在pytorch中加载参数是没问题的。
> > cfg的前几行如下：
> > [net]
> > # Testing
> > batch=1
> > subdivisions=8
> > # Training
> > # batch=32
> > # subdivisions=16
> > width=416
> > height=416
> > channels=3
> > momentum=0.9
> > decay=0.0005
> > angle=0
> > saturation = 1.5
> > exposure = 1.5
> > hue=.1
> > learning_rate=0.001
> > burn_in=1000
> > max_batches = 500200
> > max_epochs = 800
> > policy=steps
> > steps=400000,450000
> > scales=.1,.1
> > [convolutional]
> > batch_normalize=1
> > filters=32
> > size=3
> > stride=1
> > pad=1
> > activation=leaky
> > # Downsample
> > [convolutional]
> > batch_normalize=1
> > filters=64
> > size=3
> > stride=2
> > pad=1
> > activation=leaky
> > [convolutional]
> > batch_normalize=1
> > filters=32
> > size=1
> > stride=1
> > pad=1
> > activation=leaky
> 
> 看文件内容是没有问题的， 转换时是否将 darknet.cfg 作为了第一个命令行参数呢？
> 加载模型使用了darknet 的原生接口， 你可尝试使用darknet 来加载你模型试试，如果还是有问题， 考虑是否文件编码的问题了

我把cfg文件在linux下重新新建了一个拷贝过来，转成功了。原本的cfg是从Windows下拷贝过来的，可能就是编码的问题。非常感谢！

**Comment by nimu-07** [comment]
when i use the above mentioned subdivisions and height width i m getting the following error..
78 CUDA Error: out of memory
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

**Comment by xiangweizeng** [comment]
Hi,&nbsp;Insufficient GPU memory, try reducing the batch size.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nimu-07"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 晚上7:32
收件人:&nbsp;"xiangweizeng/darknet2ncnn"<darknet2ncnn@noreply.github.com&gt;;
抄送:&nbsp;"曾相未"<826127212@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [xiangweizeng/darknet2ncnn] darknet2ncnn: ./src/utils.c: 256: error: Assertion '0' failed. (#8)




when i use the above mentioned subdivisions and height width i m getting the following error..
 78 CUDA Error: out of memory
 darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
 Aborted (core dumped)
