### ISSUE TITLE
模型文件加载的方式

### ISSUE THREAD

**Issue by globalmaster** [xiangweizeng/darknet2ncnn#9]
你好，请问这个项目支持以下的模型加载方式吗？

1.加载二进制的 param.bin 和 bin
ncnn::Net net;
net.load_param_bin("alexnet.param.bin");
net.load_model("alexnet.bin");

2.从内存引用加载网络和模型
#include "alexnet.mem.h"
ncnn::Net net;
net.load_param(alexnet_param_bin);
net.load_model(alexnet_bin);

**Comment by xiangweizeng** [comment]
你好， 这两种加载模式都是ncnn的模型格式， 通过darknet2ncnn 转换后的模型， 如果不包含自定义的网络层，是可以直接使用ncnn2mem 转换为二进制使用的，  如果包含了自定义层， ncnn2mem是不直接支持的，需要做修改及调整， 目前项目中还不支持自定义的层的二进制模型加载

**Comment by xiangweizeng** [comment]
已经添加二进制参数生成及加载， 见工具 tools, example/yolo-param-bin
